### ISSUE TITLE
App updated without release 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#182]
The app shows updates today even though the new release has not been deployed. For example, the new logo has been loaded to my version on iphone, and Ellen confirms it has been deployed to both her iphone and android devices. Can we investigate how the app is updating without a release? This is concerning.

**Comment by Jiandong-Guo** [comment]
The app will be automatically updated as long as the new updated app has been uploaded to the stores,  especially for the assets such as icon, background, since they are in the different files compare to the running code.  Today I uploaded these 2 app files before noon, then I went for lunch, and then I continued with the back end process work(most typing work, and store minimizing process work) after lunch.   So seems the user will see some of the interface  change immediately after the updated app  was uploaded.
