### ISSUE TITLE
Receiving more notifications than settings menu selection 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#201]
Patricia is receiving more notifications than she has requested. Here is her information:

IPhone XR on IOS 13.6.1

I have loaded the new application version last Thursday and set my reminders to 2. I received 1 reminder not long after and another an hour or so later. But then I received 3 more notifications. On Friday, I received 7 notifications between 8:38 and 12:42. I received 8 notifications on Saturday 4 between 12:09 and 12:42 and 4 more between 15:02 and 15:52. On Sunday I received 4, 2 - 8:28 and 8:42 and 2 more 16:45 and 16:46. I am not receiving any during the do not disturb hours, but far too many during the awake hours.

**Comment by Jiandong-Guo** [comment]
get so many notifications within an hour?   search and find:
Go to Settings > Notifications > Messages and scroll down. Select Repeat Alerts and then change it from Once to Never, or however many times you want the alert to repeat. Remember, this is the number of times you want the notification to repeat, so Never means you get a single notification when the message arrives and 10 Times means you get 11 notifications: once when the message arrives, and then 10 more every two minutes.

**Comment by mullhol** [comment]
@Jiandong-Guo Patricia did have the reminder alert set to once, but that doesn't account for her receiving 8 reminders in one day when she should have only received 2.  If the reminder alert was set to once, she should have only received a maximum of 4.  So something else is still at play here.  

Also, I assume we cannot override the repeat alerts setting to ensure there are no repeat alerts for the app? 

cc @AJBouzidi

**Comment by Jiandong-Guo** [comment]
Fix Receiving Duplicate Text Message Notifications on iPhone
________________________________________
Fix 1 – Repeat Alerts Setting
There is a setting that repeats notifications which could cause this issue. Check it with these steps:
1.	From the Home screen, open “Settings“.
2.	Select “Notifications“.
3.	Choose “Messages“.
4.	Ensure that the “Repeat Alerts” setting is set to “Never“.
 
________________________________________
Fix 2 – Send & Receive Setting
Another setting that involves sending notifications to multiple numbers could be the issue as well. Check the following:
1.	From the Home screen, open “Settings“.
2.	Select “Messages“.
3.	Choose “Send & Receive“.
4.	Ensure that only your phone number is listed in the “You can be reached by iMessage at” area. If you have an email address or anything else listed, it could cause duplicate text messages.
________________________________________
Fix 3 – Toggle iMessage Off then On
Turning iMessage off then on again worked for my particular issue. You can do this by following these steps:
1.	From the Home screen, open “Settings“.
2.	Select “Messages“
3.	Slide “iMessages” to off for about 3 minutes, then turn it back on.
Your iPhone will be re-registered and may clear up the duplicate text message notification problem.

**Comment by mullhol** [comment]
@Jiandong-Guo Fix 2 and 3 are for text messages and iMessage (iPhone's version of text message when an iphone is sending to another iphone).  Before I send these to her to try, are we sure these settings would also impact local notifications?

**Comment by Jiandong-Guo** [comment]
@AJBouzidi 
I added 3 buttons in contact screen:
   LogC:   display calculated notification datetime
   LogS:   display scheduled notification(notificationId: scheduledDatetime)
   LogR:   display received notification(notificationId:scheduledDatetime),   This one is just a reference, because in some situation, the received notification won't be recorded due to the device state for example when the app is already active.

These buttons are only for test purpose, not fix anything,  I did add some code to enhance the android notification cancellation. but nothing for ios.    seems that is all we can do now.  Expo will or already have a new solution to do the notification, but seems not mention these duplicated notification issues. from the internet, there are so many discussions of the duplicated notification, they all seem to point to OS setting, and even some people said this the apple bug.

**Comment by mullhol** [comment]
Patricia made all settings revisions suggested (only one number was saved in her send and receive settings). She is now using the new version of the app and is no longer experiencing this issue.

**Comment by mullhol** [comment]
Patricia is still experiencing this issue. She updated her app this morning and has 2 notifications selected. 

Per the info button in the contact us menu, her notifications were scheduled for: 
**13:53
15:29** 

In reality she received notifications at the following times: 
_13:31_
**13:53**
_15:11_
**15:29**

**Comment by Jiandong-Guo** [comment]
Please try cancel all the notifications and reschedule notifications by changing settings to see if it can fix this problem, seems the old scheduled notifications are still there

**Comment by mullhol** [comment]
@Jiandong-Guo Patricia changed her settings and now all scheduled notifications have disappeared.

**Comment by Jiandong-Guo** [comment]
@mullhol I think she just clicked the notification switch in setting, if this switch is off, all scheduled notification will be removed, please try switch it to ON, and just change the notification number, or sleep time or wakeup time ,it will re-schedule the list

**Comment by Jiandong-Guo** [comment]
Also check:
From the Home screen, open “Settings“.
Select “Notifications“.
Choose “Messages“.
Ensure that the “Repeat Alerts” setting is set to “Never“.

**Comment by Jiandong-Guo** [comment]
sorry little confused:

Also check:
From the ### DEVICE Home screen, open “Settings“.
Select “Notifications“.
Choose “Messages“.
Ensure that the “Repeat Alerts” setting is set to “Never“.

**Comment by Jiandong-Guo** [comment]
I got this issue today. 
At 2:00PM I got 2 notifications:
         1:  Scheduled Notification   NaNTue Sept 22,2020 14:00:00...
         2: Scheduled Notification    Info:Tue Sept 22,2020 14:00:00....
then I know one is from the old app,   because The "NaN"  is bad character from the old app, and in this new release I changed to "Info:".
So every time we update or re-install the new version of the app, we have to cancel all the old scheduled notification by changing something in the setting screen. because as long as the notifications were scheduled, the control was handled to OS, even if re-installed the app, it will still pop ups

**Comment by Jiandong-Guo** [comment]
To make some correction for previous comment:
So every time BEFORE we update or uninstall the app, we have to cancel all the scheduled notification by switching the notification to OFF  in app's setting screen, AFTER the new app is installed, go back here to switch the notification back to ON.
1) The reason is the app cannot cancel another app's or even its previous version's notification. It only can cancel it's own notifications.   2) if you didn't cancel the notifications when un-install, It will still popup the notifications even it was un-installed, because the schedules have been handled to OS already.

**Comment by mullhol** [comment]
This has not been an issue for Ellen, Holly, or Trish.  Closing the ticket for the time being and will open a new ticket if SM continues to have an issue. 

In the interim, Jiandong will add version to the notification message so if this issue persists, we can determine if the notifications are coming from the old and current version of the app, or only from the current version.
