### ISSUE TITLE
Notification strategy: Missing days in schedule 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#223]
Trish downloaded the newest version of the application and received notifications for one day. After completing two questionnaire submissions, her schedule was revised leaving a multi day gap in her notification strategy. Her step by step record: 

I received my notification at 15:49 as scheduled – I completed the questionnaire at 15:52
Another one at 18:05 which was scheduled for 18:00 – I completed the questionnaire at 20:22

I did not receive any notifications last night or this morning even though my Do not disturb before is at 08:00 and Do not disturb after 23:59 was set initially.

At 10:53 I completed another questionnaire, yet I still have not received any notifications.

Went into the App around 15:30 and noticed that my Alert schedule has changed…everything is now set for Sunday.

**Comment by mullhol** [comment]
She is using Samsung Galaxy on Android 10

**Comment by mullhol** [comment]
Her original alert schedule: 

![image](https://user-images.githubusercontent.com/59370537/96271086-75c29a00-0f9a-11eb-9755-ab5508f54fa3.png)

**Comment by mullhol** [comment]
Revised alert schedule: 
![image](https://user-images.githubusercontent.com/59370537/96271142-8541e300-0f9a-11eb-9a62-425273055143.png)

**Comment by mullhol** [comment]
Rachel is now experiencing this issue as well with v 1.4.7. Her notes:

Thursday:
- 8:16 received notification five minutes late
- 9:00 completed questionnaire, checked schedule
      - Next scheduled notification not until Saturday - looked back to screenshot taken on Wednesday, that shows schedule from late Tuesday until Friday evening. 
- ~14:16 received second notification (didn't see until out of the hour) - this lines up with the schedule seen on Wednesday
- 15:25 completed questionnaire and then checked schedule - still showing only Sat and Sun

**Comment by Jiandong-Guo** [comment]
The schedule list shown when clicking Info button is only the list of schedule or re-schedule of current time. it is only for test purpose. I give a example here
Day 1:  survey A is done,  we will get the list:
         day1 :   time slut 1-1
         day1:   time slut 1-2
        ...
         day2 :   time slut 2-1
         day2:   time slut 2-2
         ...
         day3 :   time slut 3-1
         day3:   time slut 3-2
          ...
         day4 :   time slut 4-1
         day4:   time slut 4-2
        .......

if you do a survey B  on day 1,  because it is still in range,  no re-schedule needed, so the list is still there without change.
if you change setting  on day 1,  there will be a new list with 4 days or 3 days schedule in it depends on the current time.


if you do a survey B  on day 2 , the schedule function detect that you are missing one day, so it will just calculate  one day and save the one day list in that list and the old list will be overwrite. the list will show just the last day list.(day5)

if you didn't come back the day2, and you come back day3,  the schedule function detect that you are missing two days, so it will just calculate schedule list for two days and save the two-day list in that list and the old list will be overwrite. the list will show just the last-two day list.(day 6,day7)


This list is just a current calculate list for test only.  if you really want to know the whole list, we have to add code to keep the old list.

**Comment by Jiandong-Guo** [comment]
sorry, not day 6 day7, it is day5 and day 6,

**Comment by mullhol** [comment]
Schedules are correct in current version.
