### ISSUE TITLE
Notifications received from 2 versions of apps 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#229]
Both iPhone and Apple users have reported notifications being received from the previous version of the application after updating to the  latest version. This happens on the first day after upgrade only. This doubles the number of notifications they receive on the first day, as they will receive the notifications from both app versions on that day.

**Comment by Jiandong-Guo** [comment]
The reason is when the app is updated, the notification arranged by previous version is still working, so user will receive 2 set of notification. there is no way to delete those notification set by previous version, because the app was updated, the OS sees the 2 version as 2 different apps. Not sure if it can be fixed after upgrading sdk

**Comment by Jiandong-Guo** [comment]
Close according to Trish's email
