### ISSUE TITLE
Require information on how much data app consumes 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#234]
There is an FAQ concerning how much data the app uses.  IT will need to provide this information before production so we can finalize this FAQ content in the app.  

This ticket will be marked as on hold until app development is closer to completion.

**Comment by mullhol** [comment]
Once the information has been provided by IT, content for FAQ will be finalized for inclusion in the app.  Draft content is currently noted in rows 95 and 96 of the FAQ content spec.
https://gcdocs.gc.ca/statcan/llisapi.dll?func=ll&objaction=overview&objid=8007177

CC: @T-T-Nguyen

**Comment by Jiandong-Guo** [comment]
Mobile Data usage:
1) For graph: total size of 8 graphs is less than 100k,  maximum 5 times of fetching graph,  daily usage for graph is <0.5M,
2) For EQ: we don't have accurate number, but to estimate,  Survey A is much larger than the survey B, from Dlll size we can just assume survey A takes 1M, survey B takes less than 0.8M,   maximum 5 times of doing survey, daily usage for EQ is   0.8M*5=4M, we can ignore one time survey A.   so total daily 4.5M

Also from device setting Mobile data usage we can see a much smaller number for Wellbeing Check. because all the Http transfer data were compressed.
We may ask our tester to monitor for one week. the way is
1) after install our app, goto setting/Mobile Data/Well-being Check, remember the number
2) after one week, goto setting/Mobile Data/Well-being Check, remember the number
3) minus those 2 numbers
4) we average all tester's number

**Comment by mullhol** [comment]
@Jiandong-Guo In the FAQ Section under Technical difficulties, there is a question "How much data does the app require?". Here is the Response to be added: 

If you are not connected to Wi-Fi and choose to use mobile data to complete a Well-being Check, the first Well-Being Check will use approximately 1 MB. Subsequent Well-Being Checks will use less than 0.8 MB. Viewing your dashboard will use approximately 0.5 MB. Receiving notifications does not use any data.

Si vous utilisez des données mobiles au lieu d’une connexion WiFi pour remplir le Bilan bien-être, le premier bilan utilisera environ 1 Mo. Les bilans suivants utiliseront moins de 0,8 Mo. La visualisation de votre tableau de bord nécessitera environ 0,5 Mo. La réception d’avis ne nécessite aucune donnée.

CC: @t-t-nguyen

**Comment by Jiandong-Guo** [comment]
Ready for test

**Comment by Jiandong-Guo** [comment]
Close according to Trish's email
