### ISSUE TITLE
Notification Issues - E2E Prod

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#243]
Notification issues reported:

**Tester 1:** _Name of the application is in English when you get notifications.  My phone is set up in French now. Also, I think the notification are wonky….  I set my phone to get 5 notifications, but I don’t think I got 5 in the day…  3 or 4. Didn’t get my notification this morning._
**Tester 2:** _I haven’t received any notifications and had customized to 3_ 
**Tester 3:** _I only received 1 notification the first day - Initially selected 3_

**Comment by mullhol** [comment]
I am also not receiving notifications - iPhone 11. Customized to 5 per day. 

cc: @T-T-Nguyen

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo I do not have permission to assign this to you

**Comment by Jiandong-Guo** [comment]
Here is what I found:  
The way of notification function works is:
After service A or B or setting changed, app will trigger the notification schedule function,  but after service A or B done, there are couple of async functions to run before it, first is network checking, if fail, exit;  second getting jwt, if fail, exit, if everything fine, it will setPassword,  getting graphics, saving default paradata, then schedule notifications, if schedule notification  is triggered before that 2 fails, notification should be fine because they are all async. if schedule notification is not triggered and the app reports one of the fails, the notification did not get chance to be triggered.  The network detection is not a big problem, because normally if our testers find no wi-fi or network,  he will not to do the survey by common sense. but if jwt fail, that will give us lots headache.   during Azure server test, our server is much powerful(16G) than the production server(1G), jwt seldom fails, so we didn't notice this problem. right now, the production is weaker plus the jwt itself's problem,  the possibility of jwt failing is dramatically increased. so the chance of notification not getting scheduled is increased too.  after check the code,I think we can change the code a bit, we can move the notification schedule function just before the getting jwt function, so no matter jwt fail or not, we always run the schedule function.   but at this moment, we need the approval from business side, because we need spend more time to test.  Thanks  

There are 2 issues related to this problem:
1) After a survey A or B, The    if the app detects no network available,

**Comment by zhuelle** [comment]
@T-T-Nguyen Could you please confirm if the notification issue has been resolved since Beta testing? Thanks.

**Comment by zhuelle** [comment]
@Jiandong-Guo Could you please assign this ticket back to @T-T-Nguyen so she can action on it. Thanks!

**Comment by T-T-Nguyen** [comment]
This reflects the notification issues identified during E2E and will be closed.
