### ISSUE TITLE
Critical - Notification: No notifications are pushed to the device

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#282]
IOS & Android: No notifications are pushed to the device
IT can't replicate
Experienced by SOME users

**Comment by JoelleMader** [comment]
Android Redmi Note 7, MIUI version 12.5.1, Android version 10 QKQ1.190910.002, Android security patch level 2021-06-01. Verified "no restrictions" for app battery saver. Verified "notifications on" for App Notifications list. Notifications were working normally until Vital-T-Stat release last week that introduced range of bugs.

**Comment by PatMayrand** [comment]
Sylvie Legault's phone detail (has not received a single notification over the week-end): iPhone 8 v14.7.1

**Comment by T-T-Nguyen** [comment]
Narith has not received notifications over the weekend
iOS 14.6 (187F2) , Iphone Xr, the version app is 1.4.28(2.3.28)

**Comment by zhuelle** [comment]
The dev team is able to receive notification (iphone X OS 15, iPad 14 OS 12.5.4, iPhone 11 Pro OS 15, iPhone 7 OS 14.7 and iPhone 8 OS 15);
QA Tester Mory is also receiving notification (iPhone 11 OS 15.2)
@T-T-Nguyen , would you please confirm with the OID iOS testers, have they completed at least one survey and are they be able to open the Report? I know the notification is triggered after completing at least one survey.

**Comment by mpstamour** [comment]
relates to https://github.com/StatCan/WellbeingCheckUAT/issues/281

**Comment by zhuelle** [comment]
@T-T-Nguyen , I think we need to re-document this ticket. Based on what we know, all Android tests are able to receive notifications right? The iOS devices can receive notification most of cases except the case #281 when the user toggle language twice which causes the time display malfunction.

**Comment by PatMayrand** [comment]
The devices were able to receive notifications when following the "happy path". 
However, for Joelle's device (Android), her notifications are pushed only when she opens the app. She got 3 at once on this screenshot:
![Screenshot_2021-10-22-12-02-40-362_com miui home](https://user-images.githubusercontent.com/92737092/138502104-c08a79de-be4a-49ec-b782-2ecde33e2f21.jpg)

**Comment by zhuelle** [comment]
@PatMayrand Receiving multiple notification at a time is a known issue: https://confluence.statcan.ca/display/MOBILEAPP/Known+App+issues+accepted+going+into+production
Also, the previous tickets related to it are: #224 and #228

**Comment by zhuelle** [comment]
@PatMayrand The devices were able to receive notifications when following the "happy path". Do you mean Android devices or iOS devices or both? AS I know, the Android devices should not be impacted by the time picker so it should not have "Happy path" or "Un-happy path"? Thanks

**Comment by PatMayrand** [comment]
@zhuelle  Both were able to receive notifications following the happy path. However for Joelle (Android), she gets them all at the same time when opening the app. If it is a known issue and the tickets are closed, should they be reopened? Not sure what the resolution was.

**Comment by zhuelle** [comment]
@PatMayrand The dev team has spent lots of time investigated the receiving notification at the same time and there is no technical fix. This is the reason we closed the tickets before. Please see the justification in the Known App issues accepted page. Thanks.

**Comment by zhuelle** [comment]
@PatMayrand @T-T-Nguyen Like I said in my previous comments, I would suggest to redocument this ticket as:
1. The Android devices are not impacted by the time picker issue #281 so it should not have a happy or un happy path since the users can toggle language as many times as they want. Tested and can receive notifications.
2. The iOS devices are impacted by the time picker issue #281. There are "Happy path", "Semi Happy path" and "Unhappy path"
- "Happy Path" - not toggle language at Getting Start Page or any place before go into app, the users can toggle language as many times as they want in Setting, Tested and can receive notifications
- "Semi Happy Path" - Toggle language at Getting Start Page or any place before go into app, the users DO NOT toggle language in Setting, Tested and can receive notifications
- "Unhappy Path" - Toggle language at Getting Start Page or any place before go into app, the users toggle language again in Setting, this action cause Time Display malfunction, the app got locked and cannot receive notification.

**Comment by T-T-Nguyen** [comment]
To be evaluated this week

**Comment by T-T-Nguyen** [comment]
Closed - app now in Prod
To be reevaluated if this is still an issue
