### ISSUE TITLE
iOS Tester - Locked out of Account 

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#300]
iPhone, version IOS 15.
_When I clicked the link of Apple Developer, it asked me to confirm the 2 factor authentication (I haven’t activated this before with my Apple account). I then accepted and provided my phone number to get the validation code. While I never received that. 
I have tried several times and same issue. It even locked my Apple account once, that I have to reset my securities questions._

**Comment by Forum-G** [comment]
To unlock the account:
https://support.apple.com/en-ca/HT204106

I hope that link helps if not please contact apple to unlock the account.

2FA authentication:
https://support.apple.com/en-us/HT204915#:~:text=How%20to%20Turn%20on%202%20Factor%20Authentication%20on,3%20Click%20Turn%20On%20Two-Factor%20Authentication.%20See%20More.

When you scroll all way to the bottom, you will find a way to contact apple:
![image](https://user-images.githubusercontent.com/84411852/139486631-36d98717-ceda-4c77-bd00-3c6f52548445.png)

**Comment by Forum-G** [comment]
Assisted the tester on teams, the problem is she is not getting verification code on text message from apple, either she can contact them and let them know that she is not receiving the verification code in sms or she can try to get verification code from other device instead of sms:
![image](https://user-images.githubusercontent.com/84411852/139490227-c99bc0bb-39e4-44a3-aec1-419cc7afa7fc.png)
https://support.apple.com/en-us/HT204974
